name: Build and Push to Azure ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Connexion à Azure via un Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Connexion spécifique à l'ACR
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 4. Build et Push de l'image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # On utilise le tag 'latest' et le SHA du commit pour garder une trace
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/sagesse-dev:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/sagesse-dev:${{ github.sha }}
          # Utilisation du cache pour accélérer les builds futurs
          cache-from: type=gha
          cache-to: type=gha,mode=max